### PR TITLE
Add OpenBSD sparc64 support

### PR DESCRIPTION
**Pull request by bsdkurt**
Hi Greg,

I noticed you released 1.8 and would like to get this in with the next 11 release.  Almost all changes are in the sparc arch except for datatype corrections in src/hotspot/os/bsd/os_bsd.cpp and some casting in asserts in src/hotspot/share/gc/g1/g1CollectedHeap.cpp and src/hotspot/share/gc/g1/g1InCSetState.hpp. Let me know if I can merge this now or if you prefer to release 11 as is and do a second release adding this right after.

Best,
-Kurt

### CODE REVIEW

**Review by battleblow — APPROVED** [review]
Hi Kurt, sorry I didn't see your message earlier!  When you are ready to merge please let me know and I'll roll another release for JDK 11.

I didn't look over some of the Sparc specific files in detail since FreeBSD doesn't support sparc64 any longer (although I believe NetBSD does).  Everything else looked good to me.  My additional comment is that I didn't see changes to the following files:

```
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/bsd/BsdCDebugger.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/bsd/BsdThreadContextFactory.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/bsd/BsdThreadContextFactory.java
```
and I think you need to make them aware of Sparc support for the debugger to have a chance of working correctly.

Thanks for adding this!

**Comment by battleblow** [comment]
> Hi Kurt, sorry I didn't see your message earlier! When you are ready to merge please let me know and I'll roll another release for JDK 11.
> 
> I didn't look over some of the Sparc specific files in detail since FreeBSD doesn't support sparc64 any longer (although I believe NetBSD does). Everything else looked good to me. My additional comment is that I didn't see changes to the following files:
> 
> ```
> src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/bsd/BsdCDebugger.java
> src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/bsd/BsdThreadContextFactory.java
> src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/bsd/BsdThreadContextFactory.java
> ```
> 
> and I think you need to make them aware of Sparc support for the debugger to have a chance of working correctly.
> 
> Thanks for adding this!

Also

```
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/HotSpotAgent.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/runtime/Threads.java
```

I might not have caught everything there, but those also seem to need some changes

**Comment by bsdkurt** [comment]
Thanks Greg for the review and catching the missed places for the debugger support. I added it in and searched for other places with cpu.equals("sparc") I think I got them all. I have one non-sparc related fix to commit after this before we cut another release.

**Comment by battleblow** [comment]
> Thanks Greg for the review and catching the missed places for the debugger support. I added it in and searched for other places with cpu.equals("sparc") I think I got them all. I have one non-sparc related fix to commit after this before we cut another release.

I see a couple more commits since this was merged.  Let me know when you're ready and I'll roll another release :)

**Pull request merged**
